import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { Header, PlanetDetails, Planet } from "components";
import { data } from "../data";

export default function Home() {
    const planet = data[0];

    return (
        <>
            <Head>
                <title>Frontend Mentor | Planets fact site |Mercury</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>
            <Header />
            <div className={styles.main_container}>
                <Planet planet={planet} />
                <PlanetDetails planet={planet} />
            </div>
        </>
    );
}
